version: '3.8'
services:
  mongo:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./db:/data/db
    ports:
      - 27017:27017
    command: ["-f", "/etc/mongod.conf"]

  